# -*- coding: utf-8 -*-
"""automate_Moch.Faisal_Syahwaludin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJZ3SYZjOplKf3cd38_pPTYV5Z_wK6o7
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
import os

def automate_preprocessing(input_path, output_path):
    print("Memulai proses preprocessing otomatis...")

    # 1. Load dataset
    df = pd.read_csv(input_path)
    print(f"Dataset berhasil dimuat: {df.shape[0]} baris, {df.shape[1]} kolom")

    # 2. Normalisasi nama kolom
    df.columns = df.columns.str.strip().str.lower().str.replace(r'[\s\.]+', '_', regex=True)

    # 3. Hapus kolom ID
    if 'id' in df.columns:
        df.drop(columns=['id'], inplace=True)

    # 4. Rename target kolom
    if 'reached_on_time_y_n' in df.columns:
        df.rename(columns={'reached_on_time_y_n': 'reached_on_time'}, inplace=True)

    # 5. Encoding kolom kategorikal
    le = LabelEncoder()
    cat_cols = ['warehouse_block', 'mode_of_shipment', 'product_importance', 'gender']
    for col in cat_cols:
        if col in df.columns:
            df[col] = le.fit_transform(df[col])

    # 6. Standardisasi kolom numerik
    scaler = StandardScaler()
    num_cols = ['cost_of_the_product', 'discount_offered', 'weight_in_gms',
                'customer_care_calls', 'customer_rating', 'prior_purchases']
    existing_num_cols = [c for c in num_cols if c in df.columns]
    df[existing_num_cols] = scaler.fit_transform(df[existing_num_cols])

    # 7. Simpan hasil ke folder preprocessing
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False)
    print(f"File hasil preprocessing disimpan di: {output_path}")

if __name__ == "__main__":
    automate_preprocessing(
        input_path='/content/E-Commerce_Shipping_Data.csv',
        output_path='/content/e_commerce_clean.csv'
    )